server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  location / { try_files $uri $uri/ /index.html; }
  location /api/ { proxy_pass http://magic-event-manager-api:5001/; proxy_set_header Host $host; }
}
